### ISSUE TITLE
Event record model

### ISSUE THREAD

**Issue by AndrewMcBurney** [AndrewMcBurney/conductor#40]
1. An event receiver `has_many` event records.
2. An event record `belongs_to` an event receiver.
3. An event record `has_many` jobs of type `EventReceiver.job_type`.
4. A job `has_one` event record.

**Comment by AndrewMcBurney** [comment]
@davepagurek What other values do you think are important for the `EventRecord` model?

**Comment by davepagurek** [comment]
A boolean `triggered`. We would then only go through and dispatch actions if we are changing `triggered` from `false` to `true`, and not from `true` to `true`

**Comment by AndrewMcBurney** [comment]
#66
