### ISSUE TITLE
Change health_check to accept an array

### ISSUE THREAD

**Issue by davepagurek** [AndrewMcBurney/conductor#46]
The array is a 3-tuple of the average load over the past 1, 5, and 15 minutes

**Comment by AndrewMcBurney** [comment]
Is this still an issue that needs to be addressed? If so, do you want me to take it on?

**Comment by davepagurek** [comment]
Maybe keep this on hold again for now, it's probably not the most important thing. it's a nice-to-have but we still have to finish core stuff first

**Comment by andrew749** [comment]
Well just send a single value
