### ISSUE TITLE
If there is no worker to spawn job on, add a sidekiq job to periodically check until there is

### ISSUE THREAD

**Issue by davepagurek** [AndrewMcBurney/conductor#75]
e.g. there's a scheduled job, but you delete all workers before the job gets dispatched. We should handle that whenever we have sidekiq set up

**Comment by AndrewMcBurney** [comment]
Periodically check for how long? Indefinitely?

**Comment by davepagurek** [comment]
good question. maybe forever, but with exponential backoff for each successive wait? but also for the sake of time, just a fixed interval is probably fine

**Comment by AndrewMcBurney** [comment]
#79

**Comment by davepagurek** [comment]
oh hold up `ScheduledWorker.perform_at(receiver.start_time.from_now, id)` is going to wait 2017 years to retry haha, we should maybe do something like `ScheduledWorker.perform_at(RETRY_TIME.from_now, id)` where we define that to be like a half hour or something

**Comment by AndrewMcBurney** [comment]
Do we want to add `retry_time` as a property for the `EventReceiver`, and validate its existence in the `ScheduledReceiver` model?

**Comment by davepagurek** [comment]
we can probably just have it as a constant in the worker rn
