### ISSUE TITLE
Make a landing page

### ISSUE THREAD

**Issue by davepagurek** [AndrewMcBurney/conductor#84]
When you aren't signed in, it should probably have a quick rundown of features / our use case pitch.

When you are signed in, maybe have links to common tasks e.g. "see your running jobs", "create a new job template", etc

**Comment by AndrewMcBurney** [comment]
Can I just use `slim`, or do you want me to use react? lol

**Comment by davepagurek** [comment]
slim is fine, doesnt need any js

**Comment by davepagurek** [comment]
I can make a logo for it
