### ISSUE TITLE
Delete old/unused branches

### ISSUE THREAD

**Issue by AndrewMcBurney** [AndrewMcBurney/conductor#86]
We have a bunch of branches I don't think are being used anymore. Y'all mind deleting yours when you find the time? ❤️

@andrew749 
@adamklen 
@davepagurek

**Comment by andrew749** [comment]
Got rid of our stale ones. @adamklen  and @davepagurek  there are some pretty old ones that you opened.

**Comment by davepagurek** [comment]
deleted my old one
